### ISSUE TITLE
Unable to accept new Transmitter ID

### ISSUE THREAD

**Issue by Nargly** [JohanDegraeve/iosxdripreader#10]
John,

Tried to pair a new transmitter to the app tonight without success.  The ID was 40QSU1, but on entry the app responded with "Transmitter id should be 5 letter and digits" and would not take it.  I did notice that before the ID was 6 alpha numeric and worked.  Now it expects 5?  This is with the .54 test version for health kit integration.

**Comment by Nargly** [comment]
P.S. the Healthkit integration worked for a while, about 6 hours before I started having bad Bluetooth connectivity issues.  The old transmitter was about 6 months old, so I thought it may be at end of life, even though the battery level was still good.  hmmmm....

**Comment by Nargly** [comment]
P.P.S. I updated to the .54 test version due to the Bluetooth issues with the old transmitter, but .54 at first seemed strong and well with the old transmitter.  Anyway, going back to .53 and a new transmitter.  :)  Going to be on vacation next week, need this to work more flawlessly over the next week.  talk to you soon!

**Comment by JohanDegraeve** [comment]
@Nargly  I think you clicked on "Transmitter Type", which change the type from G5 to G4, you give your transmitter id but it expects 5 (G4 is 5)
Just click transmitter type again and it will switch back to G5 and ask again your transmitter id.

I'l change that : the length of the transmitter type actually also tells us what transmitter type it is. length 5 means G4, length 6 means G5 and in future numeric only will be blucon

**Comment by Nargly** [comment]
At the moment, I'm not sure I even saw that dialog asking which transmitter.  But you are likely correct.  With the healthkit integration the initial dialogs were quite overwhelming, there were a lot.  Also, I prefer the 24 hour switch on double tap rather than the large numbers.  I'll try the healthkit version again after I get back from vacation.  Keep up the great work!

**Comment by JohanDegraeve** [comment]
Yes you're right there's a bit too much initial dialogs. I'll move the healthkit to a setting.

why do you mean with the 24 hour switch on double tap ?
Actually with a single tap it goes from 6 hour display to 25 , then to large numbers and back to 6 ...

with a long press any ony of those screens, the application will stay on until you lock the phone or press the home screen

**Comment by Nargly** [comment]
Oops, 25 hour, but still a single tap for me was only showing the large numbers.  The app was being very strange at first.  It could be due to iOS 11 beta, so I wouldn't put to much into it yet.  I'll keep playing with it and let you know.

**Comment by JohanDegraeve** [comment]
it's actually 24 hour :)

**Comment by JohanDegraeve** [comment]
can be closed I assume ?

**Comment by Nargly** [comment]
Yes, and thank you.
