### ISSUE TITLE
No upload to NS till app is awakened

### ISSUE THREAD

**Issue by francesc0-cgm** [JohanDegraeve/iosxdripreader#11]
Looping with iosxdripreader and Nightoscuout share server. Often the app stops to upload till i put it in foreground.

**Comment by JohanDegraeve** [comment]
You have the latest version I assume ?

Could you send me trace file if possible (I know it's difficult because you don't know when it will stop).

I also experience it still sometimes, although it's very stable now

I could add an alert like "nightscout upload failure" or something

**Comment by Nargly** [comment]
I see this often too.  Doesn't seem to have a common cause.  Sometimes it uploads in the background, sometimes it doesn't.  (P.S. I'm still on iOS 11 beta...)

**Comment by christerjensen** [comment]
I also see it several times a day. It can some times resolve if I call my daughters phone! I think the iphone turns off mobile data.

**Comment by JohanDegraeve** [comment]
Did anyone ever experience the same with Dexcom share ?

**Comment by francesc0-cgm** [comment]
When it happened i find g5 opened by itself in background...once closed it started again working

**Comment by francesc0-cgm** [comment]
No @johanDegraeve neither on g5 nor follow

**Comment by JohanDegraeve** [comment]
It's actually the bluetooth connection that wakes up the app (from suspended to active).
It stays active for something like a minute, during that minute the app can do uploads in background.

Probably I'm using the wrong methods.

xdrip G5 ? this one also uploads in background i assume ? maybe I need to have a look in that code

**Comment by christerjensen** [comment]
If upload stops it will not resume. Iosxdripreader will continue to collect blood glucose values, and when I push the home button and awakes the phone it will magicly upload to Nightscout within seconds.

**Comment by JohanDegraeve** [comment]
You're all on the latest release ? I did a small change in 0.0.56 related to upload, but I don't know if this really improved it.

In the foreground an app can do a lot more than in the background, upload is possible at any time.
First thing being done when the app is in the foreground is to check if there's missing uploads and if yes launch an upload.

**Comment by Nargly** [comment]
Johan, Just a quick note.  I put the release version of iOS 11 on my iPhone 6s Plus 36+ hours ago.  Since then I've seen zero drop outs on uploads.  (normally before it was a few a day)  Very interesting...

**Comment by JohanDegraeve** [comment]
I also updated to iOS11 and I have a lot of problems with Nightscout upload, it almost doesn't work in the background.

Just to let you all know, I'll see if I can do anything

**Comment by Nargly** [comment]
Nightscout uploads for me are fairly good most of the time, though not in some cases of certain smartphone network connections, which is weird.  (I.e. when I'm connected at work it get short upload dropouts, rarely.  Nowhere else though...)  What's really a problem that I see is that the app drops out completely and closes during the night.  Not all the time, and no apparent reason or method to make it do that.  Of course I don't know it until I wake, go to the app and see the loading smiley and no data for a few hours.  I'm thinking iOS 11's battery saving features are far more harsh to some apps.  Could be something else though.

**Comment by JohanDegraeve** [comment]
@Nargly note that you can also use missed readings. If the app crashes then this alert will still go off.
You can plan it for instance only during sleeping hours

**Comment by JohanDegraeve** [comment]
I continue to do improvements where I think it's possible,however I don't succeed in solving the NS upload problem.

Please continue installating the latest releases.

For now I'll close this issue.
