### ISSUE TITLE
Can't find icon

### ISSUE THREAD

**Issue by rsilvers129** [JohanDegraeve/iosxdripreader#12]
On my iPhone 7+ with latest iOS the icon doesn't show up when I install with iTunes. I resigned it with ResignIPA.

Now when I try the Xcode install method, it says "There was an internal API error." I think that means that it is already installed. But I can't find it on the iPhone, even with search.

Did I get into this problem because I tried to install it with iTunes first?

**Comment by JohanDegraeve** [comment]
There is something wrong with the signing, more specific with the mobile provision file.

**Comment by rsilvers129** [comment]
I tried everything - for a few hours. Cant make it accept it. I emailed you my UUID - can you please send me an iPA? Thank you.

**Comment by rsilvers129** [comment]
Thanks. Working now.
