### ISSUE TITLE
Ambrosia BluCon

### ISSUE THREAD

**Issue by Heimdallr01** [JohanDegraeve/iosxdripreader#13]
Would it be possible to integrate support for [Ambrosia BluCon](https://www.ambrosiasys.com)?

**Comment by JohanDegraeve** [comment]
Yes I'm following the development for blucon in xdripplus.
I'll need testers.
Can you pass me your UDID ? You can send it to johan.degraeve@gmail.com

Probably tomorrow or maybe even in a few hours I'll have a test version
