### ISSUE TITLE
iOS 11

### ISSUE THREAD

**Issue by jmatheson** [JohanDegraeve/iosxdripreader#15]
Starting in iOS11 you can't install the app using the old way. You have to use the configurator (just an update to your install notes)

**Comment by JohanDegraeve** [comment]
Indeed But I think it is related to iTunes version. It is also with 10.

Github homepage is adapted.
This should also work
http://www.i-funbox.com/en_download.html
Op ma 25 sep. 2017 om 11:39 schreef Jim Matheson <notifications@github.com>
