### ISSUE TITLE
IPhone 5

### ISSUE THREAD

**Issue by danielharrelson** [JohanDegraeve/iosxdripreader#16]
Installed your latest version of iosxdripreader on an iPhone 5 with 10.3.3 and when going into settings I can turn things on and off; but, anything that requires a keyboard I am unable to edit as the keyboard never appears.

**Comment by danielharrelson** [comment]
Okay, so I realized that it has to do with my App provision...

What Application Services should I provide my provision? I think that's where they're goofed up, because I compared mine to what yours have and I'm definitely missing a few.

**Comment by JohanDegraeve** [comment]
Maybe useful to verify the entitilements file :
Take my ipa (here) and yours.
Change extension to .zip, unpack them.
In a terminal session, go to the folder Payload

Then type 
codesign -d --entitlements :- "appname.app"
Except for the application id, the contents should be the same

**Comment by JohanDegraeve** [comment]
One other tip ,
if you install "Apple 2 configurator" on your mac, then open again a terminal session and connect your iphone to your mac.

/Applications/Apple\ Configurator\ 2.app/Contents/MacOS/cfgutil syslog | grep -i entitlement
Start the app and go to settings where things turn off, you could see a log related to a problem with entitlement, that would point to a code signing problem.

or 
/Applications/Apple\ Configurator\ 2.app/Contents/MacOS/cfgutil syslog | grep -i xdripreader
(assuming you named the app something with xdripreader in it)
You will maybe see why it crashes.

**Comment by danielharrelson** [comment]
```
daniel@Daniels-iMac:~/iPhone5/iosxdripreader/Payload$ codesign -d --entitlements :- "iosxdripreader.app"
Executable=/Users/daniel/iPhone5/iosxdripreader/Payload/iosxdripreader.app/iosxdripreader
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>application-identifier</key>
        <string>8DKSZ5HNLB.net.johandegraeve.iosxdripreader</string>
        <key>get-task-allow</key>
        <true/>
        <key>aps-environment</key>
        <string>development</string>
        <key>com.apple.developer.healthkit</key>
        <true/>
        <key>keychain-access-groups</key>
        <array>
            <string>8DKSZ5HNLB.*</string>
        </array>
    </dict>
</plist>
daniel@Daniels-iMac:~/iPhone5/iosxdripreader/Payload$ codesign -d --entitlements :- ../../iosxdripreader-resigned/Payload/"iosxdripreader.app"
Executable=/Users/daniel/iPhone5/iosxdripreader-resigned/Payload/iosxdripreader.app/iosxdripreader
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>application-identifier</key>
        <string>G62E2Z2NL3.com.danielharrelson.iosxdripreader</string>
        <key>aps-environment</key>
        <string>production</string>
        <key>com.apple.developer.healthkit</key>
        <true/>
        <key>com.apple.developer.siri</key>
        <true/>
        <key>com.apple.developer.team-identifier</key>
        <string>G62E2Z2NL3</string>
        <key>com.apple.external-accessory.wireless-configuration</key>
        <true/>
        <key>com.apple.security.application-groups</key>
        <array/>
        <key>get-task-allow</key>
        <false/>
        <key>keychain-access-groups</key>
        <array>
                <string>G62E2Z2NL3.*</string>
        </array>
</dict>
</plist>

```

**Comment by danielharrelson** [comment]
I gave my app a lot more permissions than you did. It's odd, because mine does not have "Cellular Data" rights.

**Comment by JohanDegraeve** [comment]
Strange indeed, your list seems to be longer,

Do you find anything in the logs, with cfgutil ?

**Comment by danielharrelson** [comment]
Inexperience on my part. Problem resolved. :)
