### ISSUE TITLE
doubt with ipa file to install for nightrider

### ISSUE THREAD

**Issue by pocoyo01** [JohanDegraeve/iosxdripreader#19]
Hello, first of all a million thanks for your work. My name is Jose and I am trying to set up a system to see my young son's glucose from work. My son uses freestyle and has an iphone 6, I bought a nightrider (ambrosia system) that will come home in a few weeks and I intend to send his readings to the iphone using the application iosdripreader, the case is that I do not know the 3 ipa files install, I have an apple developer license, so I can sign ipa without problems. Forgive my English, I am Spanish and I am using the google translator.
Many thanks.
regards

**Comment by JohanDegraeve** [comment]
Did you succeed in resigning ? you can take any of them :
For example https://github.com/JohanDegraeve/iosxdripreader/releases/download/1.1.2/iosxdripreader.ipa

**Comment by pocoyo01** [comment]
Thank you, I have already installed that file. Installation without problems, as I do not have the nightrider I can not pair it to test, that if I can not enter the data of Nightsout in the preferences section, no keyboard is deployed to intrude the values.
Thank you

**Comment by Mondelman** [comment]
Hi Pocoyo01, I'm Spanish too, let me talk Spanish.
No entiendo exactamente qué problema tienes, ya que esta aplicación "habla" directamente con el Blucon, Limitter o Bluereader.
¿Cuál tienes tú?
Saludos,

Miguel

**Comment by JohanDegraeve** [comment]
If the keyboard doesn't show up, you probably made an error in the resigning.
In the gitter room there are some people who have more experience, maybe you can ask for support

https://gitter.im/nightscout/iosxdripreader

It would be good if you can do the resigning yourself

**Comment by pocoyo01** [comment]
Buenos dias, os comento, no soy lo que se dice precisamente un experto en informatica, el caso es que estoy preparando para montar un sistema de monitoreo continuo para el freestyle que lleva mi hijo. Todos en la familia tenemos ipnone, y he comprado en ambrosia system un nightrider pero aun no me ha llegodo pero estoy intentando ir montando todo para cuando llegue. Tengo entendido por lo que he leido que la aplicacion iosxdripreader recibe la informacion de nightrider en el telefono de mi hijo, y este por medio de la misma manda los datos a la plataforma nightscout para que desde los telefonos de los padres podamos ver los valores en tiempo real. 
El caso es que he instalado el ipa en un telefono ya y he entrado en configuracion para ir conociendo en la aplicacion pero me he dado cuenta que el teclado no funciona por ejemplo para introducier la url y contraseña en el apartado de nightcout.
Muchas gracias a todos por la ayuda.
De verdad sinceras gracias.

Good morning, I'm telling you, I'm not the one who says exactly a computer expert, but I'm preparing to set up a continuous monitoring system for my son's freestyle. Everyone in the family has ipnone, and he bought the ragweed system, but it has not yet come to me, but I'm trying to mount everything by the time I get there. I understand by what he read that the application iosxdripreader receives the information of the night in the phone of my son, and this by means of the same sends the data to the platform of the night so that from the phones of the parents we can see the values ​​in real time
The case is that he installed the ipa on a phone and entered the settings to get to know the application, but I realized that the keyboard does not work for example to enter the url and password in the nightcout section.
Thank you very much everyone for the help.
Really sincere thanks.

**Comment by JohanDegraeve** [comment]
one remark :
"..the same sends the data to the platform of the night so that from the phones of the parents we can see the values in real time.."

for the moment there is no ios application that reads from NightScout if the app is in the background. Foreground yes, but background no.

I plan to do this but the only solution is to have an app released in iTunes (long explanation which I will not give here) , this will take more time

**Comment by pocoyo01** [comment]
Many thanks for the clarification, I understand then that I would have to always have the application open on my phone to see my son's values. By the way I do not know very well how to fight with the program for the keyboard theme. Thank you

**Comment by JohanDegraeve** [comment]
yes this works https://itunes.apple.com/us/app/nightguard/id1116430352?mt=8
but keep the app in the foreground during the night

can you post your resigning problem in https://gitter.im/nightscout/iosxdripreader ? Maybe Mondelman can help ?

**Comment by pocoyo01** [comment]
thanks Johan.
