### ISSUE TITLE
Widget / Watch support and other problems

### ISSUE THREAD

**Issue by Schoggiweggli** [JohanDegraeve/iosxdripreader#24]
Are there plans to implement a Widget like the one Dexcom or Ambrosia BluCon app has? or even Apple Watch support?. 

The constant notifications work, but i find them inferior to a widget. What annoys me the most is that the screen turns on every time the notification pops up. Drains the battery and disturbs at night. 

Someone suggested to turn off lockscreen notification for the app and viewing it via notification center. That's a good idea, but it doesn't work since iOS 11 new notification system.

For the watch i currently use nightguard, which displays the nightscout data.

**Comment by JohanDegraeve** [comment]
Yes someone will make an attempt to create a Watch app.

I don't have the impression that the 'screen turn on' drains the battery.
During the night I put it screen downward, the screen doesn't lite up then and it doesn't drain the battery.

**Comment by Schoggiweggli** [comment]
Sounds reasonable, thanks for the information. 

I use a BluCon, another problem i have is that the bluetooth connection seems to drop afer a while (maybe i walk out of range and i doesn't come back). But it locks it up somehow, not even the original app can re-establish a connection, flight mode or even rebooting the phone didn't help either. I have to delete and reconnect the device to get it recognized again.

Also, when i listen to a podcasts or music with bluetooth headphones, opening the xDrip app pauses the audio. Not sure if it's bluetooth related, haven't tried it with wired headphones.

Maybe there is a problem with my phone? i am using an iPhone SE.
Works fine with xDrip on android though, so i don't blame the BluCon.

**Comment by miguelkennedy** [comment]
Schoggiweggli are you using the latest version of the app available here in this github page? The audio problem should have been fixed in the latest version...

**Comment by Schoggiweggli** [comment]
@miguelkennedy i use version 1.1.18 with iOS 11.2, it happend again today. I installed it over the older version without deleting it first.

**Comment by miguelkennedy** [comment]
Regarding pausing the audio, go to the app settings and try it with the "override mute" on and also with off... See if any of these settings help.

**Comment by Schoggiweggli** [comment]
@miguelkennedy tested it today, these settings don't matter. The audio still pauses upon opening xDrip, it affects audio with or without headphones, bluetooth or wired. Maybe it's a model specific thing ?

**Comment by JohanDegraeve** [comment]
Regarding connection drops, i've got a test version aiming at improving blucon connection stability.
Signed for group1 (iosxdripreader.ipa) and group5.
@schoggiweggli what group are you in ?

**Comment by caiuscristian** [comment]
@Schoggiweggli I also tried the LinkBluCon app with the Apple Watch, but it crashes every hour or so and does not reconnect. It's not usable atm. 

Rarely I get a reconnection problem, where I need first need to open the xDrip app again and keep it open until it reconnects automatically within a couple of minutes. Other than that I have to say that xDrip 1.1.18 is very stable with BluCon and works great! GREAT work guys!

**Comment by Schoggiweggli** [comment]
@JohanDegraeve i am in group4.
@caiuscristian i don't really use the watch that often and the drops happen anyway, so i do not blame it on this. Reopen does not help in my case, it doesn't come back. Which iPhone model do you use ?

**Comment by caiuscristian** [comment]
@Schoggiweggli No, it's not the watch. Its the LinkBluCon app itself. For me it crashes constantly as well. I use an iPhone 7 Plus, running iOS 11.2.

**Comment by miguelkennedy** [comment]
Schoggiweggli: what app do you use to listen to music and podcasts? I want to see if I can recreate the pause bug using the same apps as you.

Also, when you start the xDrip the audio pauses but if you go into the music/podcasts app and resume it it continues to play without interruption? Even if xDrip fires an alarm sound at the same time?

**Comment by Schoggiweggli** [comment]
@miguelkennedy i use the standard Podcast and Music app from Apple. It also happens with other apps like TuneIn Radio or any other i suppose.

Yes if i resume the music it plays normal unless i switch to xDrip. It plays also normal inside xDrip when i resume it via control center. I don't know what happens when an alarm goes off, had none during listening. So it's caused when xDrip comes into focus, then it stops.

@caiuscristian yeah, it's pretty horrible anyway.

**Comment by JohanDegraeve** [comment]
@miguelkennedy maybe it's because we set AVAudioSessionCategoryOptionMixWithOthers by default
https://github.com/JohanDegraeve/ANE-BackgroundFetch/blob/master/ios/AirBackgroundFetch/AirBackgroundFetch.m#L102 ?

Maybe we need to make that configurable, in an advance settings option section

**Comment by JohanDegraeve** [comment]
I tried today wired headset and with bluetooth speaker
The sound doesn't interrupt when bringing the app in the foreground, also not when alert goes off or readings are spoken.

But it did stop when actualling launching the app: app is closed, music (spotify) playing - wired. Then launch app, music stopped
Also on iPhone SE.

Is this the problem you have @Schoggiweggli

**Comment by Schoggiweggli** [comment]
@JohanDegraeve exactly. I  imagine that it happend sporadically when bringing the app to the foreground, but that doesn't happen to me with 1.1.30, up until now. I have no active sensor at the moment but i will keep an eye on it later.

**Comment by Schoggiweggli** [comment]
Regarding the dis/reconnect issue with a BluCon, it seems pretty solid with 1.1.30. Had no issues over the last 24h as i had with previous verions. I hope it will stay that stable.

**Comment by moccon** [comment]
just installed Xdrip and this works way better on my iPhone 6+ than the original Ambrosia app.  (lost connection and time outs)  Really like the Speech function.

**Comment by Schoggiweggli** [comment]
Maybe i don't get it but how exactly does vibration work? i enabled vibration during a low alarm but the phone doesn't vibrate. Is that only for when the phone itself is muted?

**Comment by JohanDegraeve** [comment]
It should vibrate if you enable it in the alert type. 
But at least one other person reported to have a problem with it.

Can you send me your UDID, I'll do another test with a small modification

**Comment by Schoggiweggli** [comment]
I sent it via email. I'm currently on 1.1.32 from TestFlight. No vibration with iPhone SE & X

**Comment by moccon** [comment]
Hi Johan, also using xDrip via TestFlight on iPhone 6 plus, no vibriton here..
