### ISSUE TITLE
Bluetooth wixel support

### ISSUE THREAD

**Issue by tommy-gansta** [JohanDegraeve/iosxdripreader#27]
hello, I am using old config of wixel on HM 10 without voltage devider and do want to pair it with iOs version of xDrip. on andorid I have an option without setting transmitter ID. but on version 1.1.30 if I set G4, app cannot get data. so is it hard to support of old config? without ble and with stable connection

**Comment by JohanDegraeve** [comment]
can hou install this wxl ?
https://1drv.ms/u/s!AoD_n2ttq1dEgsRSIodaZ7S6M960Zg
In the ios xdrip app, chose transmitter type G4 and set correct transmitter id

And in home screen scan for the device

**Comment by tommy-gansta** [comment]
it works for me. thanks a lot!
