### ISSUE TITLE
Feature Request: Apple Health/Insulin-Carbs

### ISSUE THREAD

**Issue by dansuk** [JohanDegraeve/iosxdripreader#31]
Would it be possible to add support to allow a basic entry of Insulin and Carbs which would be logged to Apple Health and/or Nightscout? The way Xdrip populates the glucose data into Apple Health is great and if could log insulin and carbs as well would allow integration with other glucose logbook apps which already support Apple Health/Nightscout?

**Comment by JohanDegraeve** [comment]
It's certainly possible. Probably I'll work on it because I also need this. I'm using another app for the moment but I want to integrate this in xdrip. Inclusive a carbohydrate counter with a food composition table.

I don't know when and it will certainly take some development time

**Comment by dansuk** [comment]
Thanks Johan, that sounds great!

**Comment by JohanDegraeve** [comment]
Will not be added in iosxdrip. Planned for Spike
