### ISSUE TITLE
How long need to wait invite?

### ISSUE THREAD

**Issue by Jezze83** [JohanDegraeve/iosxdripreader#32]
What is response time for invite? I sended email week ago and not response yet.

**Comment by JohanDegraeve** [comment]
This can vary from a few minutes to half a day.
Probably I missed yours. Can you resend it please ? xdrip@proximus.be

**Comment by Jezze83** [comment]
Sended

**Comment by JohanDegraeve** [comment]
Invite was already sent on january 6th actually
resent now

**Comment by Jezze83** [comment]
Hmm, i use different email address for sending email. So that invite email goes to my itunes account email inbox?

**Comment by JohanDegraeve** [comment]
yes
