### ISSUE TITLE
Disable notifications on every 5mins

### ISSUE THREAD

**Issue by Jezze83** [JohanDegraeve/iosxdripreader#35]
How i can disable notifications for every new measure? I want keep alarms on for low and high but xdrip spam every 5mins for new measure.

**Comment by JohanDegraeve** [comment]
In the settings , "readings in notification", click so that it switches to "off"

**Comment by Jezze83** [comment]
I found bug. If bluetooth connection disconnect between xdrip and nightrider, that xdrip start spamming again every 5mins and readings in notification id disabled. Works fine before bluetooth disconnecting.

**Comment by JohanDegraeve** [comment]
can you enable detailed tracing, wait till it occurs (ie blucon disconnected but you get the notification every 5 minutes), then send detailed tracing

thanks

**Comment by Jezze83** [comment]
How i send that? I cant add any email address when i enable dateled tracing

**Comment by JohanDegraeve** [comment]
after the test, click "send trace file via e-mail", the to address is xdrip@proximus.be and will be prefilled

you must have an e-mail account configured in your ios settings (meaning if you use for instance a gmail client only, the email will not be sent)

**Comment by Jezze83** [comment]
I use only gmail app so i cant send that file, right? Now i cant get that spamming to stop. I enabled that and disabled but still spamming.

**Comment by JohanDegraeve** [comment]
It will not send the email if no email account is configured in your iOS settings.

**Comment by Jezze83** [comment]
Sended

**Comment by JohanDegraeve** [comment]
There's not one log that indicates you got a notification with the new value.

There are however 15 notifications asking for a calibration. This is a silent notification (no sound, no vibration), probably you're confusing it with the notification that gives your value.

You can either calibrate or change the calibration alert. Set to no alert, or specify a longer calibration period (eg 24 or 48). I don't now how often calibration is necessary to get good values

**Comment by Jezze83** [comment]
Xdrip not asking any calibration when i open app. Nightrider monitoring works fine.

**Comment by Bull3time** [comment]
I have been noticing that notifications aren't always replicating to my apple watch, I suspect it is an apple bug but I wondered what ability you have to change notification behaviour? I.e. would it be possible to do an alert that vibrates, as a configuration option?

I might enable tracing and see if I can replicate any of the periods where notifications don't sync in case it highlights anything, or rules it out.

**Comment by JohanDegraeve** [comment]
To test you could configure a low alert with a high value, that vibrates each time.

The app logs will not help to resolve this. Maybe iOS logs but I don't know what to look for on those logs.
If you have a mac I can help you retrieving those logs
