### ISSUE TITLE
iOS xdrip

### ISSUE THREAD

**Issue by type1diabetic** [JohanDegraeve/iosxdripreader#38]
Trying to see how to get iOS x drip on iPhone 6 for the g4 dexcom?  To be able to share glucose

**Comment by JohanDegraeve** [comment]
You have an xdrip or xbridge ?
If yes send your email address to xdrip@proximus.be

**Comment by type1diabetic** [comment]
I don’t have anything I just got a replacement transmitter and was told I needed the xdrip app to share readings!

**Comment by JohanDegraeve** [comment]
With G4 you need the Xdrip to make it work, example https://xdripkit.co.uk/
