### ISSUE TITLE
Status not showing

### ISSUE THREAD

**Issue by Schoggiweggli** [JohanDegraeve/iosxdripreader#40]
On version 1.4.0 the status screen (Bluetooth icon -> Status) is not showing up. At least for me, already did a reinstall.

**Comment by moccon** [comment]
Same here

**Comment by JohanDegraeve** [comment]
can you try with the previous version, it's still available via testflight

**Comment by Schoggiweggli** [comment]
Yes, it worked fine with 1.3.1

**Comment by moccon** [comment]
No problem just mentioning

**Comment by JohanDegraeve** [comment]
very strange, I just re-installed from TestFlight and for me it works

**Comment by moccon** [comment]
Iphone 6+,   was not on latest version, updating iPhone now!

**Comment by Schoggiweggli** [comment]
very strange indeed. i updated again from 1.3.1 to 1.4.0 and it stopped working as before, iPhone X.

**Comment by JohanDegraeve** [comment]
If you have a mac, can you 

Install apple 2 configurator https://itunes.apple.com/be/app/apple-configurator-2/id1037126344?mt=12
connect iphone
open a terminal session 
type
/Applications/Apple\ Configurator\ 2.app/Contents/MacOS/cfgutil syslog | grep -i xdripreader

See if there's any crash at the moment you click the bluetooth icon and if yes  post here

**Comment by moccon** [comment]
after updating iphone the same its doesnt matter) but WORKAROUND:
I opend Testflight choosed previous version, i did NOT deleted my old version before doing that.
Now i have the latest version (at leasts it says so) and status is working again.

**Comment by JohanDegraeve** [comment]
You probably have the previous version, but latest version is stored in database. So you re-install a previous version, and it still says it's 1.4.0
Looks like a new bug

anyway, why status dialog is not shown, very strange

**Comment by moccon** [comment]
cant see that from here, updating now to test what happends.

**Comment by Schoggiweggli** [comment]
Nothing critial i suppose? here is the log anyway:

`Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogViewController::create: 5
Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:create
Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogViewController::getViewByIdentifier: 562
Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:[562]:show
Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:[562]:show: Adding option: Status [0:4]
Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:[562]:show: Adding option: Stop sensor [0:3]
Feb  6 16:27:57 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:[562]:show: Adding option: Cancel [1:6]
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: activate generator <UISelectionFeedbackGenerator: 0x1c812e240: prepared=1> with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: activate feedback engine 0x1c00c9060, clientCount: 0 -> 1
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: activating engine
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: feedback engine <_UIFeedbackHapticOnlyEngine: 0x1c00c9060: state=0, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Inactive -> Activating
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: starting haptics player
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(AudioToolbox)[735] <Notice>: 385: clientID: 0x10002df numberOfChannels: 20
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [SpringBoard:62] Attempting to acquire assertion for iosxdripreader:735: <BKProcessAssertion: 0x10491b630; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&C3EC7CCF00BD>
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Add assertion: <BKProcessAssertion: 0x10491b630; id: 62-1709F072-9FBB-4927-BF0C-C3EC7CCF00BD; name: com.apple.UIKit.KeyboardManagement.message; state: active; reason: finishTask; duration: 180.0s> {    owner = <BSProcessHandle: 0x104b045c0; SpringBoard:62; valid: YES>;
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Activate assertion: <BKProcessAssertion: 0x10491b630; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&C3EC7CCF00BD>
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Setting jetsam priority to 10 [0x10108]
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: performing AVHapticPlayer async call allocateRenderResourcesWithCompletionHandler:
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(AudioToolbox)[735] <Notice>: 439: allocating resources: clientID: 0x10002df
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: performed AVHapticPlayer async call allocateRenderResourcesWithCompletionHandler:
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: performing AVHapticPlayer async call startRunningWithCompletionHandler:
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(AudioToolbox)[735] <Notice>: 541: start running: clientID: 0x10002df
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.NetworkInfo::findInterfaces()
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Deactivate assertion: <BKProcessAssertion: 0x10491b630; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&C3EC7CCF00BD>
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (deactivateAssertion): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Setting jetsam priority to 10 [0x10100]
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Remove assertion: <BKProcessAssertion: 0x10491b630; "com.apple.UIKit.KeyboardManagement.message" (finishTask:180s); id:\M-b\M^@\M-&C3EC7CCF00BD>
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader[735] <Notice>: [xdripreadertrace ANE-BackgroundFetch] AirBackgroundFetch_playSound
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: performed AVHapticPlayer async call startRunningWithCompletionHandler:
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 2854: { "action":"activate", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 2910: { "action":"activate", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":null }
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4400: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4549: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":{"IOs":[0,1,0,0,0],"IsRecording":false,"active":true,"modes":"Output","player":"0x138868400","state":"Priming","type":"Queue"} }
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4400: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(CoreMedia)[29] <Notice>: -CMSessionMgr- cmsSetIsPlaying: CMSession: 'sid:0x24b78, iosxdripreader(735), 'prim'' with [MediaPlayback/Default] [Mixable] [System Audio] starting playing.
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Attempting to acquire assertion for iosxdripreader:735: <BKProcessAssertion: 0x104b16e30; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&58CD2BCD9D07>
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Add assertion: <BKProcessAssertion: 0x104b16e30; id: 29-6C1F9B2E-6953-4DBE-B143-58CD2BCD9D07; name: CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion; state: active; reason: audio; duration: infs> {    owner = <BSProcessHandle: 0x104903a80; mediaserverd:29; valid: YES>;
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Activate assertion: <BKProcessAssertion: 0x104b16e30; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&58CD2BCD9D07>
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Canceled allow-idle-sleep timer
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] New process assertion state; preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, preventIdleSleep, preventSuspendOnSleep (assertion 0x104b16e30 added: preventIdleSleep; removed: (none))
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Setting jetsam priority to 10 [0x10101]
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
<BKProcessAssertion: 0x104b16e30; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&58CD2BCD9D07> [active]
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: Creating PowerAssertion on iosxdripreader:735
Feb  6 16:27:58 Apple-iPhone-X powerd[42] <Notice>: Process assertiond.77 Created SystemIsActive "iosxdripreader:735:29-6C1F9B2E-6953-4DBE-B143-58CD2BCD9D07 [CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion] [0x104b16e30]" age:00:00:00  id:51539648205 [System: PrevIdle SysAct]
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4549: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":{"IOs":[0,1,0,0,0],"IsRecording":false,"active":true,"modes":"Output","player":"0x138868400","state":"Started","type":"Queue"} }
Feb  6 16:27:58 Apple-iPhone-X assertiond[77] <Notice>: Created PowerAssertion on iosxdripreader:735, sleep reverted
Feb  6 16:27:58 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 194: AQME device AQDefaultDevice: client starting: <AudioQueueObject@0x138868400; sid:0x24b78, iosxdripreader(735), 'prim'; play>; running count now 1
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: engine turned ON
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: haptics player started
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: feedback engine <_UIFeedbackHapticOnlyEngine: 0x1c00c9060: state=3, numberOfClients=1, prewarmCount=0, _isSuspended=0> state changed: Activating -> Running
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: deactivate generator <UISelectionFeedbackGenerator: 0x1c812e240: prepared=0> with style: TurnOn; activationCount: 1 -> 0; styleActivationCount: 1 -> 0
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: deactivate feedback engine 0x1c00c9060, clientCount: 1 -> 0
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: _deactivateEngineIfPossible <_UIFeedbackHapticOnlyEngine: 0x1c00c9060: state=4, numberOfClients=0, prewarmCount=0, _isSuspended=0>, clientCount: 0, suspended: 0
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: _teardownUnderlyingPlayerIfPossible <_UIFeedbackHapticOnlyEngine: 0x1c00c9060: state=4, numberOfClients=0, prewarmCount=0, _isSuspended=0>, _freeChannelIndexes.count: 20
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: stopping haptics player
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: engine turned OFF
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(AudioToolbox)[735] <Notice>: 565: stop running: clientID: 0x10002df
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: _deactivateEngineIfPossible <_UIFeedbackHapticOnlyEngine: 0x1c00c9060: state=4, numberOfClients=0, prewarmCount=0, _isSuspended=0> tearedDown: 1
Feb  6 16:27:58 Apple-iPhone-X iosxdripreader(UIKit)[735] <Notice>: feedback engine <_UIFeedbackHapticOnlyEngine: 0x1c00c9060: state=4, numberOfClients=0, prewarmCount=0, _isSuspended=0> state changed: Running -> Inactive
Feb  6 16:27:59 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:[562]:handleAction: 4
Feb  6 16:27:59 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogViewController::dismissed: 562
Feb  6 16:27:59 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogViewController::disposeViewByIdentifier: 562
Feb  6 16:27:59 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogViewController::getViewByIdentifier: 562
Feb  6 16:27:59 Apple-iPhone-X iosxdripreader[735] <Notice>: com.distriqt.Dialog::DTDADialogView_ActionSheet:[562]:dismiss
Feb  6 16:27:59 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 390: AQME device AQDefaultDevice: client stopping: <AudioQueueObject@0x138868400; sid:0x24b78, iosxdripreader(735), 'prim'; play>; running count now 0
Feb  6 16:27:59 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4400: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:27:59 Apple-iPhone-X mediaserverd(CoreMedia)[29] <Notice>: -CMSessionMgr- cmsSetIsPlaying: CMSession: 'sid:0x24b78, iosxdripreader(735), 'prim'' with [MediaPlayback/Default] [Mixable] [System Audio] stopping playing.
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: Client relinquished <BKProcessAssertion: 0x104b16e30; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&58CD2BCD9D07>
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Deactivate assertion: <BKProcessAssertion: 0x104b16e30; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&58CD2BCD9D07>
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (deactivateAssertion): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Scheduling allow-idle-sleep timer with interval: 180.0
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] New process assertion state; preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, preventSuspendOnSleep (assertion 0x104b16e30 added: (none); removed: preventIdleSleep)
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Setting jetsam priority to 10 [0x10100]
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:27:59 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4549: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":{"IOs":[0,0,0,0,0],"IsRecording":false,"active":true,"modes":"Output","player":"0x138868400","state":"Stopped","type":"Queue"} }
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: Releasing PowerAssertion on iosxdripreader:735 from update
Feb  6 16:27:59 Apple-iPhone-X powerd[42] <Notice>: Process assertiond.77 Released SystemIsActive "iosxdripreader:735:29-6C1F9B2E-6953-4DBE-B143-58CD2BCD9D07 [CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion] [0x104b16e30]" age:00:00:00  id:51539648205 [System: PrevIdle SysAct]
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Remove assertion: <BKProcessAssertion: 0x104b16e30; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&58CD2BCD9D07>
Feb  6 16:27:59 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {
Feb  6 16:28:03 Apple-iPhone-X iosxdripreader[735] <Notice>: [xdripreadertrace ANE-BackgroundFetch] AirBackgroundFetch_playSound
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 2854: { "action":"activate", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 2910: { "action":"activate", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":null }
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4400: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4549: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":{"IOs":[0,1,0,0,0],"IsRecording":false,"active":true,"modes":"Output","player":"0x138868400","state":"Priming","type":"Queue"} }
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4400: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(CoreMedia)[29] <Notice>: -CMSessionMgr- cmsSetIsPlaying: CMSession: 'sid:0x24b78, iosxdripreader(735), 'prim'' with [MediaPlayback/Default] [Mixable] [System Audio] starting playing.
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Attempting to acquire assertion for iosxdripreader:735: <BKProcessAssertion: 0x104b18520; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&32AFFEFAFD7C>
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Add assertion: <BKProcessAssertion: 0x104b18520; id: 29-1DC627CF-BF03-48D2-BF15-32AFFEFAFD7C; name: CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion; state: active; reason: audio; duration: infs> {    owner = <BSProcessHandle: 0x104903a80; mediaserverd:29; valid: YES>;
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Activate assertion: <BKProcessAssertion: 0x104b18520; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&32AFFEFAFD7C>
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Canceled allow-idle-sleep timer
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] New process assertion state; preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, preventIdleSleep, preventSuspendOnSleep (assertion 0x104b18520 added: preventIdleSleep; removed: (none))
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Setting jetsam priority to 10 [0x10101]
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
<BKProcessAssertion: 0x104b18520; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&32AFFEFAFD7C> [active]
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: Creating PowerAssertion on iosxdripreader:735
Feb  6 16:28:03 Apple-iPhone-X powerd[42] <Notice>: Process assertiond.77 Created SystemIsActive "iosxdripreader:735:29-1DC627CF-BF03-48D2-BF15-32AFFEFAFD7C [CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion] [0x104b18520]" age:00:00:00  id:51539648206 [System: SysAct]
Feb  6 16:28:03 Apple-iPhone-X assertiond[77] <Notice>: Created PowerAssertion on iosxdripreader:735, sleep reverted
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4549: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":{"IOs":[0,1,0,0,0],"IsRecording":false,"active":true,"modes":"Output","player":"0x138868400","state":"Started","type":"Queue"} }
Feb  6 16:28:03 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 194: AQME device AQDefaultDevice: client starting: <AudioQueueObject@0x138868400; sid:0x24b78, iosxdripreader(735), 'prim'; play>; running count now 1
Feb  6 16:28:04 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 390: AQME device AQDefaultDevice: client stopping: <AudioQueueObject@0x138868400; sid:0x24b78, iosxdripreader(735), 'prim'; play>; running count now 0
Feb  6 16:28:04 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4400: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":"entry" }
Feb  6 16:28:04 Apple-iPhone-X mediaserverd(CoreMedia)[29] <Notice>: -CMSessionMgr- cmsSetIsPlaying: CMSession: 'sid:0x24b78, iosxdripreader(735), 'prim'' with [MediaPlayback/Default] [Mixable] [System Audio] stopping playing.
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: Client relinquished <BKProcessAssertion: 0x104b18520; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&32AFFEFAFD7C>
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Deactivate assertion: <BKProcessAssertion: 0x104b18520; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&32AFFEFAFD7C>
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (deactivateAssertion): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Scheduling allow-idle-sleep timer with interval: 180.0
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] New process assertion state; preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, preventSuspendOnSleep (assertion 0x104b18520 added: (none); removed: preventIdleSleep)
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Setting jetsam priority to 10 [0x10100]
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:28:04 Apple-iPhone-X mediaserverd(AudioToolbox)[29] <Notice>: 4549: { "action":"set_play_state", "session":{"ID":"0x24b78","PID":735,"name":"iosxdripreader"}, "details":{"IOs":[0,0,0,0,0],"IsRecording":false,"active":true,"modes":"Output","player":"0x138868400","state":"Stopped","type":"Queue"} }
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: Releasing PowerAssertion on iosxdripreader:735 from update
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] Remove assertion: <BKProcessAssertion: 0x104b18520; "CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion" (audio:inf); id:\M-b\M^@\M-&32AFFEFAFD7C>
Feb  6 16:28:04 Apple-iPhone-X assertiond[77] <Notice>: [iosxdripreader:735] dump all assertions HWM:6 (CPUMON check): {    <BKProcessAssertion: 0x104a25460; "Resume" (activation:inf); id:\M-b\M^@\M-&97B851B9D16C> [active]
Feb  6 16:28:04 Apple-iPhone-X powerd[42] <Notice>: Process assertiond.77 Released SystemIsActive "iosxdripreader:735:29-1DC627CF-BF03-48D2-BF15-32AFFEFAFD7C [CMSession.735."net.johandegraeve.iosxdripreader"."MediaPlayback".isPlayingProcessAssertion] [0x104b18520]" age:00:00:00  id:51539648206 [System: PrevIdle SysAct]`

**Comment by JohanDegraeve** [comment]
Ok I could reproduce. Will fix

Op di 6 feb. 2018 om 16:32 schreef Schoggiweggli <notifications@github.com>
