### ISSUE TITLE
Value change within alert notification

### ISSUE THREAD

**Issue by caiuscristian** [JohanDegraeve/iosxdripreader#41]
Hi,

I think I asked this already once and it got implemented at some point. 

It would be great to also view the trend arrow and the value difference from the last reading directly within the xDrip notificaion. It is very useful on the go to know, that my glucose level is not only low, or high but also that it's dropping or rising fast. 

Best
Cristian

**Comment by JohanDegraeve** [comment]
That’s indeed supported already

Op wo 7 feb. 2018 om 14:10 schreef Cristian CC <notifications@github.com>

**Comment by caiuscristian** [comment]
Ah, ok. Sry, my bad. I meant in the alters notifications. It only shows up in the notification readings that show the readings every 5 minutes.

Could you please also implement it for the high, very high, low and very low alerts? Atm it only shows the actual value.

**Comment by JohanDegraeve** [comment]
ok i see what you mean.

Yes I can do that

**Comment by Nargly** [comment]
Another yes vote on this feature.  I also wondered often why the arrow didn't represent the change better, sloping differently on the amount of movement.  That's no big deal though, but food for thought.

**Comment by Violacaddeo** [comment]
Non riesco a cancellarmi dal thread...Ho provato diverse volte ma non riesco. Mi aiutatemi??

Inviato da Yahoo Mail su Android 
 
  Il mer, 7 feb, 2018 alle 15:50, Nargly<notifications@github.com> ha scritto:   
Another yes vote on this feature. I also wondered often why the arrow didn't represent the change better, sloping differently on the amount of movement. That's no big deal though, but food for thought.

**Comment by hummelstrand** [comment]
@JohanDegraeve If you want to implement better arrows, I'd be happy to share SVG files for the following arrows that I created as a suggestion for "nightguard": 
![image](https://user-images.githubusercontent.com/2979793/35926296-1af86078-0c28-11e8-9fe2-be356284898f.png)

**Comment by JohanDegraeve** [comment]
I can only add text in the notification, even there I had some problem with the double arrow up.
You can see it's actually two characters, each of them representing one arrow up

**Comment by JohanDegraeve** [comment]
is this ok ?
De full text doesn't fit in the bold part (the alert title)

![27783602_10215614590028632_443658752_n](https://user-images.githubusercontent.com/13840461/35947499-6b81c382-0c68-11e8-95b7-85fc5256525a.png)

**Comment by Nargly** [comment]
If an option, the second lower notification is most acceptable.  Both are great though!  Thanks for the effort.

**Comment by JohanDegraeve** [comment]
The second is the normal always on notification (every 5 minutes).

The first one is a modified low alert notification.
If I put everything on the same line, it may get too long and iOS shortens it to ...
Example  
![27994299_10215617050650146_582855530_n](https://user-images.githubusercontent.com/13840461/35964440-0b535b10-0cb8-11e8-84eb-0d1fd1f6b0cf.png)
