### ISSUE TITLE
Transmiter pl : alert if sensor age not increasing for 10 minutes

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/iosxdripreader#42]
If sensor age not incremented by 1 every 10 minutes = sensor is expired (if time is greather than 20160/10 = 14 days) or dead (if time is shorter).
in those cases formal alerm should be triggered - "Dead or Expired Sensor"
as a protection for mistakes - condition for this alarm can be confirmed by few (3-5) consecutive BG values received from Transmiter. In case of dead/expired - will be the same in each incoming data from Transmiter.

**Comment by FPV-UAV** [comment]
Implementation OK. Issue can be closed :)
