### ISSUE TITLE
implement local web server compatible with loop

### ISSUE THREAD

**Issue by dabear** [JohanDegraeve/iosxdripreader#43]
Would it be possible to publish glucose values to a local embedded web server, for example using https://github.com/thecatalinstan/Criollo/wiki/Getting-Started in a dexcom share like protocol?

If you can implement the following two url paths, Loop will be able to fetch glucose values directly, and offline.

1.  HTTP POST "?accountname=foobar&password=234&applicationid=234" to
http://localhost/ShareWebServices/Services/General/LoginPublisherAccountByName.

return value must be a valid GUID but can be random. Examples of valid GUIDs:
```
"4c9a3161-a931-424b-a424-18b3a954972b"
"82ed3bca-0010-4e27-bf66-9e26c163fe46"
"fb2268a9-a9bd-4af7-a02d-0be41df91fc4"
```
Guids must start with and end with quotation marks to be JSON compliant.

2. HTTP GET to http://localhost/ShareWebServices/Services/Publisher/ReadPublisherLatestGlucoseValues
```
[{"DT":"\/Date(1518213156131+0000)\/","ST":"\/Date(1518213156131+0000)\/","Trend":4,"Value":166,"WT":"\/Date(1518213156131)\/"},{"DT":"\/Date(1518212976131+0000)\/","ST":"\/Date(1518212976131+0000)\/","Trend":3,"Value":163,"WT":"\/Date(1518212976131)\/"}]
```
The "DT" and "ST" fields are not used by loop

I've created an example page that is usable with Loop if you compile Loop with support for custom dexcom share server sites:
http://mockedshareserver.azurewebsites.net/ShareWebServices/Services/Publisher/ReadPublisherLatestGlucoseValues

**Comment by francesc0-cgm** [comment]
Great idea @dabear

**Comment by JohanDegraeve** [comment]
solved in spike https://spike-app.com
