### ISSUE TITLE
Improve bluetooth connectivity

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/iosxdripreader#6]
**Current implementation** : 
iphone is scanning almost all the time.
Evert 5 minutes, Dexcom G5 transmitter has a new value , it starts broadcasting, iphone discovers the transmitter and wakes up the iosxdripreader app and will connect, read the value, synchronize with NightScout, check alerts etcetera.
The app immediately stops the scanning here, because it has received signal from the transmitter it is waiting for. 

The app sets a timer at that moment for 10 seconds later, If this timer expires, it's supposed to restart the scanning. Why stop scanning when the transmitter is discovered ? because apparently the Dexcom transmitter just keeps on broadcasting after this process, for a maximum of around 7  seconds. This is probably because Dexcom transmitter can connect to multiple devices (Dexcom iphone app and the separate reader). But I don't want the app to connect a second time, so that's why I stopped scanning.
A few seconds later the timer exipires, and scanning will retart.
About a minute later the app is suspended by iOS. That's how iOS behaves : apps that have no reason to stay active are suspended. That's why the timer is set 10 seconds later, before it is being suspended. If I would set a timer for instance 4min45 seconds later, it wouldn't expire, because iOS would have put the app in suspended mode.

And 5 minutes later everything restarts.
Now it may happen, or I was assuming it may happen that this timer doesn't expire. So I had a fallack : which is a spare iphone at home sending a silent notification every 5 minutes to each device. In fact each device that installed and launched the app. This notification is sent about 30 to 90 seconds after a reading is supposed to be received. It awakens the app and gives the app the opportunity the verify the scanning status, if the device is not scanning, it will start scanning.

Just last week (around 5th of July), I switched off that spare iphone (the app on the spare iphone  has been runnning for 6 monhts, here's the app that runs on the spare iphone https://github.com/JohanDegraeve/pushnotification

This week I received from one user a complaint that the app is not stable anymore. After analysing the log files I concluded that in some cases this timer doesn't expiry, and since my pushnotification app is not running ... the app simply stopped scanning and never restarted.

For an app running in the foreground this is all no problem : the timer will expire, iOS doesn't suspend the app.
Also when going from background to foreground, it's doing a scan status check (don't remember where but I think it does :) )

**New implementation**
The app should never stop scanning. To avoid connecting to the transmitter more than once, it should simply ingore the second discovery.
I should remove this line https://github.com/JohanDegraeve/iosxdripreader/blob/master/src/services/BluetoothService.as#L424
and when discovery happens : https://github.com/JohanDegraeve/iosxdripreader/blob/master/src/services/BluetoothService.as#L372
check first of the last reading is less than 5 minutes old, if so ignore this discovery

If that doesn't help, then I'll have to work on the fallback solution. It needs to be more reboust, eg what in case of electricty failure in my house , ... or WiFi failure

**Comment by Nargly** [comment]
I'm on iOS 11 beta, so I thought that was what the problem was.  The OS seems to be much more aggressive at battery saving, and the drop outs appeared to only occur while the phone was asleep and screen off.  After turning back on the screen, and going back into that app on the next 5 min mark the readings would come back.  It is very random otherwise, as it doesn't always drop out when asleep.

**Comment by JohanDegraeve** [comment]
Anyone who wants to test with this fix ? https://1drv.ms/u/s!AoD_n2ttq1dEk9Q5LkWzmZIoE0_X7w

**Comment by Nargly** [comment]
Just installed and testing :)

**Comment by Nargly** [comment]
After a little more than 1/2 a day, it only drops out one reading once in a while.  But returns to reading values on the next 5 min interval on it's own without interaction which is different than before.  When it dropped out before, you had to take action to get them back.  Usually just opening the app, sometimes removing and re-pairing the Bluetooth connection.  One possible new thing, the uploads to nightscout are dropping out and will not return until you re-open the xdrip app to see the readings.  I'm trying now to pay attention to if this occurs as the same time the single reading misses occur.

**Comment by JohanDegraeve** [comment]
I also have the same results, after almost 24 hour of testing.
Nightscout upload is a differen thing.

I'm going to release a version 0.0.50 within a few hours, together with some other changes, like mmol in the chart.

**Comment by JohanDegraeve** [comment]
@Nargly thanks for testing and feedback
