### ISSUE TITLE
G4 tester needed

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/iosxdripreader#8]
For those who are subscribed here and receiving this notification, could someone test this version ?
https://1drv.ms/u/s!AoD_n2ttq1dElIpUkEt1DL-8B6zG5g

Just see if you can still connect to xdrip/xbridge and receive at least one reading.

**Comment by Nargly** [comment]
Installed and testing.  This time is was rather difficult to start up.  The Bluetooth connection required resetting, and the app never asked for a BG calibration after the first attempt at the Bluetooth reset (20 mins waiting).  Second time on Bluetooth reset worked.  Then it asked for 3 BG calibrations before finally showing a value.  I don't recall if it asked for the first reading twice or the second reading twice, but it was definitely 3 asks.
After the 3rd ask, and a showing value I found 3 values had uploaded to Nightscout.  I'll keep an eye on it and give you an update tomorrow.

**Comment by Mondelman** [comment]
Is G4 compatible with this version? No xBridge required? WOW
Thanks for commenting, Johan

**Comment by JohanDegraeve** [comment]
@Mondelman  xbridge or xdrip is still required

**Comment by JohanDegraeve** [comment]
@Nargly indeed I mean G4, i'm also on G5. I did a few changes as preparation for BluCon support, just want to be sure it's still working for G4

**Comment by Mondelman** [comment]
Then I can't help you, Johan. Sorry.
